apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application }}-service-{{ .Values.profile }}
  labels:
    {{- include "seongyun-application.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "seongyun-application.selectorLabels" . | nindent 4 }}
