spring:
  application:
    name: spring-playground-api
  profiles:
    active: ${SPRING_PROFILE:local}
  config:
    import:
      - application-jpa.yml

management.endpoint.health.probes.enabled: on
