name: Test

on:
  push:
    branches:
      - 'test/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo ${{github.sha}}_${{github.ref_name}}
          echo $GITHUB_REF
          echo $GITHUB_REF_NAME
