name: API Push Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt-openj9

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER_NAME }}
          password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}

      - name: Jib
        run: |
          ./gradlew :spring-playground-api:jib \
            -PregistryRepository=${{ secrets.REGISTRY_USER_NAME }}/github-action-test
